import "%modules%/header/header";
import "%modules%/footer/footer"
import "%modules%/slider/slider"
import "../../blocks/modules-pages/articles/articles";
import "../../blocks/modules-pages/header-page/header-page";
import "../../blocks/modules-pages/header-page/header-page";
import "../../blocks/modules-pages/register-form/register-form";
import "../../blocks/modules-pages/info-profile/info-profile";
import "../../blocks/modules-pages/shop/shop";
import "../../blocks/modules-pages/decors-cat/decors-cat";
import "../../blocks/modules-pages/filter/filter";
import "../../blocks/modules-pages/actions-vn/actions-vn";
import "../../blocks/modules-pages/support-vn/support-vn";
import "../../blocks/modules-pages/auth-form/auth-form";